name: Typst CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      TYPST_PACKAGE_PATH: packages
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@e00d2c94cc0067b77737821097a62d91c0301baa # v1.21.1
        with:
          version: "1.21.1"
      - name: Install Typst tooling (typstyle & tytanic)
        run: cargo binstall --no-confirm tytanic@0.4.1 typstyle@0.15.1
      #- name: Install typst-package-check
      #  run: cargo install --git https://github.com/typst/package-check.git
      #- name: Check package
      #  run: typst-package-check check
      - name: Check formatting with typstyle
        run: typstyle --check .
      - name: Run regression tests with tytanic
        run: tt run
