name: Typst CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install Typst tooling (typstyle & tytanic)
        run: cargo binstall tytanic typstyle
      - name: Install typst-package-check
        run: cargo install --git https://github.com/typst/package-check.git
      - name: Check package
        run: typst-package-check check
      - name: Check formatting with typstyle
        run: typstyle --check .
      - name: Run regression tests with tytanic
        run: tt run
